using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class RandomStringForMenu : MonoBehaviour
{
    public Animator WordAnimation;
    public MenuManagement menuManagement;
    public static string SyncWord;
    public Text[] DisplayText;
    public string[] WordDictionary;

    private string RawWord =
    "AAHAALAASABAABSABYACEACTADDADOADSADZAFFAFTAGAAGEAGOAGSAHAAHIAHSAIDAILAIMAINAIRAISAITALAALBALEALLALPALSALTAMAAMIAMPAMUANAANDANEANIANTANYAPEAPOAPPAPTARBARCAREARFARKARMARSARTASHASKASPATEATTAUKAVAAVEAVOAWAAWEAWLAWNAXEAYEAYSAZOBAABADBAGBAHBALBAMBANBAPBARBASBATBAYBEDBEEBEGBELBENBESBETBEYBIBBIDBIGBINBIOBISBITBIZBOABOBBODBOGBOOBOPBOSBOTBOWBOXBOYBRABROBRRBUBBUDBUGBUMBUNBURBUSBUTBUYBYEBYSCABCADCAMCANCAPCARCATCAWCAYCEECELCEPCHICIGCISCOBCODCOGCOLCONCOOCOPCORCOSCOTCOWCOXCOYCOZCRUCRYCUBCUDCUECUMCUPCURCUTCWMDABDADDAGDAHDAKDALDAMDANDAPDAWDAYDEBDEEDEFDELDENDEVDEWDEXDEYDIBDIDDIEDIFDIGDIMDINDIPDISDITDOCDOEDOGDOLDOMDONDORDOSDOTDOWDRYDUBDUDDUEDUGDUHDUIDUNDUODUPDYEEAREATEAUEBBECUEDHEDSEEKEELEFFEFSEFTEGGEGOEKEELDELFELKELLELMELSEMEEMSEMUENDENGENSEONERAEREERGERNERRERSESSETAETHEVEEWEEYEFABFADFANFARFASFATFAXFAYFEDFEEFEHFEMFENFERFESFETFEUFEWFEYFEZFIBFIDFIEFIGFILFINFIRFITFIXFIZFLUFLYFOBFOEFOGFOHFONFOPFORFOUFOXFOYFROFRYFUBFUDFUGFUNFURGABGADGAEGAGGALGAMGANGAPGARGASGATGAYGEDGEEGELGEMGENGETGEYGHIGIBGIDGIEGIGGINGIPGITGNUGOAGOBGOOGORGOSGOTGOXGOYGULGUMGUNGUTGUVGUYGYMGYPHADHAEHAGHAHHAJHAMHAOHAPHASHATHAWHAYHEHHEMHENHEPHERHESHETHEWHEXHEYHICHIDHIEHIMHINHIPHISHITHMMHOBHODHOEHOGHONHOPHOSHOTHOWHOYHUBHUEHUGHUHHUMHUNHUPHUTHYPICEICHICKICYIDSIFFIFSIGGILKILLIMPINKINNINSIONIREIRKISMITSIVYJABJAGJAMJARJAWJAYJEEJETJEUJEWJIBJIGJINJOBJOEJOGJOTJOWJOYJUGJUNJUSJUTKABKAEKAFKASKATKAYKEAKEFKEGKENKEPKEXKEYKHIKIDKIFKINKIPKIRKISKITKOAKOBKOIKOPKORKOSKUEKYELABLACLADLAGLAMLAPLARLASLATLAVLAWLAXLAYLEALEDLEELEGLEILEKLESLETLEULEVLEXLEYLEZLIBLIDLIELINLIPLISLITLOBLOGLOOLOPLOTLOWLOXLUGLUMLUVLUXLYEMACMADMAEMAGMANMAPMARMASMATMAWMAXMAYMEDMEGMELMEMMENMETMEWMHOMIBMICMIDMIGMILMIMMIRMISMIXMOAMOBMOCMODMOGMOLMOMMONMOOMOPMORMOSMOTMOWMUDMUGMUMMUNMUSMUTMYCNABNAENAGNAHNAMNANNAPNAWNAYNEBNEENEGNETNEWNIBNILNIMNIPNITNIXNOBNODNOGNOHNOMNOONORNOSNOTNOWNTHNUBNUNNUSNUTOAFOAKOAROATOBAOBEOBIOCAODAODDODEODSOESOFFOFTOHMOHOOHSOILOKAOKEOLDOLEOMSONEONOONSOOHOOTOPEOPSOPTORAORBORCOREORSORTOSEOUDOUROUTOVAOWEOWLOWNOXOOXYPACPADPAHPALPAMPANPAPPARPASPATPAWPAXPAYPEAPECPEDPEEPEGPEHPENPEPPERPESPETPEWPHIPHTPIAPICPIEPIGPINPIPPISPITPIUPIXPLYPODPOHPOIPOLPOMPOOPOPPOTPOWPOXPROPRYPSIPSTPUBPUDPUGPULPUNPUPPURPUSPUTPYAPYEPYXQATQISQUARADRAGRAHRAIRAJRAMRANRAPRASRATRAWRAXRAYREBRECREDREEREFREGREIREMREPRESRETREVREXRHORIARIBRIDRIFRIGRIMRINRIPROBROCRODROEROMROTROWRUBRUERUGRUMRUNRUTRYARYESABSACSADSAESAGSALSAPSATSAUSAWSAXSAYSEASECSEESEGSEISELSENSERSETSEWSHASHESHHSHYSIBSICSIMSINSIPSIRSISSITSIXSKASKISKYSLYSOBSODSOLSOMSONSOPSOSSOTSOUSOWSOXSOYSPASPYSRISTYSUBSUESUKSUMSUNSUPSUQSYNTABTADTAETAGTAJTAMTANTAOTAPTARTASTATTAUTAVTAWTAXTEATEDTEETEGTELTENTETTEWTHETHOTHYTICTIETILTINTIPTISTITTODTOETOGTOMTONTOOTOPTORTOTTOWTOYTRYTSKTUBTUGTUITUNTUPTUTTUXTWATWOTYEUDOUGHUKEULUUMMUMPUNSUPOUPSURBURDURNURPUSEUTAUTEUTSVACVANVARVASVATVAUVAVVAWVEEVEGVETVEXVIAVIDVIEVIGVIMVISVOEVOWVOXVUGVUMWABWADWAEWAGWANWAPWARWASWATWAWWAXWAYWEBWEDWEEWENWETWHAWHOWHYWIGWINWISWITWIZWOEWOKWONWOOWOSWOTWOWWRYWUDWYEWYNXISYAGYAHYAKYAMYAPYARYAWYAYYEAYEHYENYEPYESYETYEWYINYIPYOBYODYOKYOMYONYOUYOWYUKYUMYUPZAGZAPZASZAXZEDZEEZEKZEPZIGZINZIPZITZOAZOOZUZZZZ";
    public void Start()
    {
        int WordCount = 0;
        string CutString = "";
        for (int i = 0; i < RawWord.Length; i++)
        {
            CutString = CutString + RawWord[i];

            if (CutString.Length == 3)
            {

                WordDictionary.SetValue(CutString, WordCount);

                WordCount++;
                CutString = "";
            }

        }
        StartCoroutine(DisplayTextRandom());
       
    }

    IEnumerator DisplayTextRandom()
    {
        while (true)
        {
           
                WordAnimation.SetTrigger("NextWord");
                yield return new WaitForSeconds(0.5f);
          
            int RandomIndex = Random.Range(0, WordDictionary.Length);
            SyncWord = WordDictionary[RandomIndex];
            for (int i = 0; i < DisplayText.Length; i++)
            {
                DisplayText[i].text = SyncWord[i].ToString();
            }
           
             WordAnimation.SetTrigger("ReadyNextWord");
            yield return new WaitForSeconds(1.8f);
            

            if (menuManagement.GetClickedForSynce() == true)
            {
                break;
            }

        }

    }


}
